const path = require('path');

module.exports = {
  useCachedSchedule: true,
  csvPath: path.join(__dirname, 'responses.csv'),
  competitionStartTime: '09:00',
  competitionEndTime: '16:30',
  blockDurationMinutes: 30,
  lunchStart: '13:00',
  lunchEnd: '14:00',
  numberOfDays: 1,
  scheduleDay: 'saturday',
  optimizationIterations: 1,
  columnMap: {
    email: 'Email Address',
    driveTeam: 'Driveteam',
    wantsPits: 'Are you interested in being on pit crew?',
    pit: 'Pit',
    otherRoles: 'What other roles are you interested in?',
    roles: 'Roles',
    media: 'Media',
    strategy: 'Strategy',
    journalism: 'Journalism',
    technicalSpokesperson: 'Technical spokesperson',
    outreachSpokesperson: 'Outreach spokesperson',
    whichDays: 'Which days will you be attending?',
    friday: 'Friday',
    saturday: 'Saturday',
    nametag: 'Nametag',
    nametagRevised: 'Nametag (Revised)',
    anythingElse: 'Anything else about your availability or preferences?',
    pitCrewUnderstand: 'Do you understand that pit crew will require working with a manager ahead of time to prepare for the role?',
    pitWorkType: 'What type of pit work are you interested in?',
    mechPit: 'Mech Pit',
    ctrlsPit: 'Ctrls Pit',
    swPit: 'SW Pit',
    timesOfDay: 'What times of day are you interested in?',
  },
};
